#!/bin/bash

input_daytimewallpaper=''
input_nighttimewallpaper=''
daytimewallpaper=''
nighttimewallpaper=''
location=''

print_usage() {
  echo "Usage: smart-wallpaper [FLAG]"
  echo "  Flags:"
  echo "    [-d]: NEEDED   : daytime wallpaper file/folder"
  echo "    [-n]: NEEDED   : nighttime wallpaper file/folder"
  echo "    [-l]: OPTIONAL : manual location, if not added geoclue gets the location (requires internet)"
  echo "    [-h]: OPTIONAL : print help message"
}

set_wallpaper() {
  if [[ $1 == *".gif" ]] && [ -f /usr/bin/gifview ]; then
    gifview --animate -w root $1
  else
    #killall gifview# every 500h secs its settings the wallpaper but is it necessary (check if gifview proc?)
    feh --bg-fill $1
  fi
}

if (( $# == 0 )); then
    print_usage
    exit 1
fi

while getopts 'd:n:l:h' flag; do
  case "${flag}" in
    d) input_daytimewallpaper="${OPTARG}"    ;;
    n) input_nighttimewallpaper="${OPTARG}"  ;;
    l) location="${OPTARG}"                  ;;
    h) print_usage
       exit 0                                ;;
    *) print_usage
       exit 1                                ;;
  esac
done

if [ "$input_daytimewallpaper" == "" ]; then
  print_usage
  exit 1
fi

if [ "$input_nighttimewallpaper" == "" ]; then
  print_usage
  exit 1
fi

daytimewallpaper=$(find $input_daytimewallpaper -type f | shuf -n 1)
nighttimewallpaper=$(find $input_nighttimewallpaper -type f | shuf -n 1)

while true
do

  if [ "$location" != "" ]; then
    string=$(redshift -l $location -p)
    shopt -s nocasematch
    if [[ $string == *"day"* ]]; then
      set_wallpaper "$daytimewallpaper"
    else
      set_wallpaper "$nighttimewallpaper"
    fi
    shopt -u nocasematch
  else
    string=$(redshift -p)
    shopt -s nocasematch
    if [[ $string == *"day"* ]]; then
      set_wallpaper "$daytimewallpaper"
    else
      set_wallpaper "$nighttimewallpaper"
    fi
    shopt -u nocasematch
  fi

  sleep 500s
done
