#!/bin/bash

trap cleanup EXIT

period=500

input_daytimewallpaper=''
input_nighttimewallpaper=''
daytimewallpaper=''
nighttimewallpaper=''
location=''

currenttime='pn5Lf1f8SH' #random string so the first loop works
timebool=false
procid=''

cleanup() {
  if [[ $procid != '' ]]; then
    kill $procid
  fi
}

print_usage() {
  echo "Usage: smart-wallpaper [FLAG]"
  echo "  Flags:"
  echo "    [-d]: NEEDED   : daytime wallpaper file/folder"
  echo "    [-n]: NEEDED   : nighttime wallpaper file/folder"
  echo "    [-l]: OPTIONAL : manual location (lat:long), if not added geoclue gets the location (requires internet)"
  echo "    [-t]: OPTIONAL : set the time period (seconds) for the script to check if it is day or night "
  echo "    [-h]: OPTIONAL : print help message"
}

set_wallpaper() {

  if [[ $procid != '' ]]; then
    kill $procid
  fi

  if [[ $1 == *".gif" ]] && [ -f /usr/bin/gifview ]; then
    gifview --animate -w root $1 &
    procid=$!
  else
    feh --bg-fill $1
    procid=''
  fi

}

checktime() {
  if [ "$location" != "" ]; then
    if redshift -l $location -p | grep -i -q "$currenttime"; then
      timebool=true
    else
      timebool=false
    fi
  else
    if redshift -p | grep -i -q "$currenttime"; then
      timebool=true
    else
      timebool=false
    fi
  fi
}

if (( $# == 0 )); then
    print_usage
    exit 1
fi

while getopts 'd:n:l:t:h' flag; do
  case "${flag}" in
    d) input_daytimewallpaper="${OPTARG}"    ;;
    n) input_nighttimewallpaper="${OPTARG}"  ;;
    t) period="${OPTARG}"                    ;;
    l) location="${OPTARG}"                  ;;
    h) print_usage
       exit 0                                ;;
    *) print_usage
       exit 1                                ;;
  esac
done

if [ "$input_daytimewallpaper" == "" ]; then
  print_usage
  exit 1
fi

if [ "$input_nighttimewallpaper" == "" ]; then
  print_usage
  exit 1
fi

daytimewallpaper=$(find $input_daytimewallpaper -type f | shuf -n 1)
nighttimewallpaper=$(find $input_nighttimewallpaper -type f | shuf -n 1)

while true
do

  checktime

  if [ $timebool == false ]; then
    if [ "$location" != "" ]; then
      if redshift -l $location -p | grep -i -q "day"; then
        currenttime="day"
        set_wallpaper "$daytimewallpaper"
      else
        currenttime="night"
        set_wallpaper "$nighttimewallpaper"
      fi
    else
      if redshift -p | grep -i -q "day"; then
        currenttime="day"
        set_wallpaper "$daytimewallpaper"
      else
        currenttime="night"
        set_wallpaper "$nighttimewallpaper"
      fi
    fi
  fi

  sleep $period
done
